require "love.filesystem"
require "love.image"
local imageData = {}
imageData[0] = love.image.newImageData("asset/UI/matchScene/content/OD/ODLight_0.png")
imageData[1] = love.image.newImageData("asset/UI/matchScene/content/OD/ODLight_1.png")
imageData[2] = love.image.newImageData("asset/UI/matchScene/content/OD/ODLight_2.png")
imageData[3] = love.image.newImageData("asset/UI/matchScene/content/OD/ODLight_3.png")
imageData[4] = love.image.newImageData("asset/UI/matchScene/content/OD/ODLight_4.png")
imageData[5] = love.image.newImageData("asset/UI/matchScene/content/OD/ODLight_5.png")

imageData[6] = love.image.newImageData("asset/UI/matchScene/content/timeNumber/0.png")
imageData[7] = love.image.newImageData("asset/UI/matchScene/content/timeNumber/1.png")
imageData[8] = love.image.newImageData("asset/UI/matchScene/content/timeNumber/2.png")
imageData[9] = love.image.newImageData("asset/UI/matchScene/content/timeNumber/3.png")
imageData[10] = love.image.newImageData("asset/UI/matchScene/content/timeNumber/4.png")
imageData[11] = love.image.newImageData("asset/UI/matchScene/content/timeNumber/5.png")
imageData[12] = love.image.newImageData("asset/UI/matchScene/content/timeNumber/6.png")
imageData[13] = love.image.newImageData("asset/UI/matchScene/content/timeNumber/7.png")
imageData[14] = love.image.newImageData("asset/UI/matchScene/content/timeNumber/8.png")
imageData[15] = love.image.newImageData("asset/UI/matchScene/content/timeNumber/9.png")
imageData[16] = love.image.newImageData("asset/UI/matchScene/content/timeNumber/colon.png")

imageData[17] = love.image.newImageData("asset/UI/matchScene/content/abilityGauge.png")
imageData[18] = love.image.newImageData("asset/UI/matchScene/content/dangerP1.png")
imageData[19] = love.image.newImageData("asset/UI/matchScene/content/dangerP2.png")
imageData[20] = love.image.newImageData("asset/UI/matchScene/content/healthGauge.png")
imageData[21] = love.image.newImageData("asset/UI/matchScene/content/heatGauge.png")
imageData[22] = love.image.newImageData("asset/UI/matchScene/content/negativePenaltyP1.png")
imageData[23] = love.image.newImageData("asset/UI/matchScene/content/negativePenaltyP2.png")
imageData[24] = love.image.newImageData("asset/UI/matchScene/content/overdriveText.png")
imageData[25] = love.image.newImageData("asset/UI/matchScene/content/plus.png")
imageData[26] = love.image.newImageData("asset/UI/matchScene/content/positiveBonusText.png")
imageData[27] = love.image.newImageData("asset/UI/matchScene/content/positiveBounsP1.png")
imageData[28] = love.image.newImageData("asset/UI/matchScene/content/positiveBounsP2.png")
imageData[29] = love.image.newImageData("asset/UI/matchScene/content/riskGauge.png")
imageData[30] = love.image.newImageData("asset/UI/matchScene/content/roundLight.png")
imageData[31] = love.image.newImageData("asset/UI/matchScene/content/UIUpper.png")

imageData[32] = love.image.newImageData("asset/UI/matchScene/gauge/abilityGauge.png")
imageData[33] = love.image.newImageData("asset/UI/matchScene/gauge/healthGauge.png")
imageData[34] = love.image.newImageData("asset/UI/matchScene/gauge/heatGauge.png")
imageData[35] = love.image.newImageData("asset/UI/matchScene/gauge/heatGauge.png")
imageData[36] = love.image.newImageData("asset/UI/matchScene/gauge/OD.png")
imageData[37] = love.image.newImageData("asset/UI/matchScene/gauge/overdriveText.png")
imageData[38] = love.image.newImageData("asset/UI/matchScene/gauge/riskGauge.png")
imageData[39] = love.image.newImageData("asset/UI/matchScene/gauge/roundLightGauge.png")

love.thread.getChannel( 'image' ):push( imageData )