require "love.filesystem"
require "love.image"
local imageData = {}
imageData[0] = love.image.newImageData("asset/UI/matchScene/content/OD/0.png")
imageData[1] = love.image.newImageData("asset/UI/matchScene/content/OD/1.png")
imageData[2] = love.image.newImageData("asset/UI/matchScene/content/OD/2.png")
imageData[3] = love.image.newImageData("asset/UI/matchScene/content/OD/3.png")
imageData[4] = love.image.newImageData("asset/UI/matchScene/content/OD/4.png")
imageData[5] = love.image.newImageData("asset/UI/matchScene/content/OD/5.png")

imageData[6] = love.image.newImageData("asset/UI/matchScene/content/time_number/0.png")
imageData[7] = love.image.newImageData("asset/UI/matchScene/content/time_number/1.png")
imageData[8] = love.image.newImageData("asset/UI/matchScene/content/time_number/2.png")
imageData[9] = love.image.newImageData("asset/UI/matchScene/content/time_number/3.png")
imageData[10] = love.image.newImageData("asset/UI/matchScene/content/time_number/4.png")
imageData[11] = love.image.newImageData("asset/UI/matchScene/content/time_number/5.png")
imageData[12] = love.image.newImageData("asset/UI/matchScene/content/time_number/6.png")
imageData[13] = love.image.newImageData("asset/UI/matchScene/content/time_number/7.png")
imageData[14] = love.image.newImageData("asset/UI/matchScene/content/time_number/8.png")
imageData[15] = love.image.newImageData("asset/UI/matchScene/content/time_number/9.png")
imageData[16] = love.image.newImageData("asset/UI/matchScene/content/time_number/colon.png")

imageData[17] = love.image.newImageData("asset/UI/matchScene/content/ability_light.png")
imageData[18] = love.image.newImageData("asset/UI/matchScene/content/danger_P1.png")
imageData[19] = love.image.newImageData("asset/UI/matchScene/content/danger_P2.png")
imageData[20] = love.image.newImageData("asset/UI/matchScene/content/health_light.png")
imageData[21] = love.image.newImageData("asset/UI/matchScene/content/heat_indicator.png")
imageData[22] = love.image.newImageData("asset/UI/matchScene/content/heat_light.png")
imageData[23] = love.image.newImageData("asset/UI/matchScene/content/negative_penalty_P1.png")
imageData[24] = love.image.newImageData("asset/UI/matchScene/content/negative_penalty_P2.png")
imageData[25] = love.image.newImageData("asset/UI/matchScene/content/overdrive_indicator.png")
imageData[26] = love.image.newImageData("asset/UI/matchScene/content/plus.png")
imageData[27] = love.image.newImageData("asset/UI/matchScene/content/positive_bonus_text.png")
imageData[28] = love.image.newImageData("asset/UI/matchScene/content/positive_bouns_P1.png")
imageData[29] = love.image.newImageData("asset/UI/matchScene/content/positive_bouns_P2.png")
imageData[30] = love.image.newImageData("asset/UI/matchScene/content/risk_light.png")
imageData[31] = love.image.newImageData("asset/UI/matchScene/content/match_point_light.png")
imageData[32] = love.image.newImageData("asset/UI/matchScene/content/UI_upper.png")

imageData[33] = love.image.newImageData("asset/UI/matchScene/gauge/ability_gauge.png")
imageData[34] = love.image.newImageData("asset/UI/matchScene/gauge/health_gauge.png")
imageData[35] = love.image.newImageData("asset/UI/matchScene/gauge/heat_gauge.png")
imageData[36] = love.image.newImageData("asset/UI/matchScene/gauge/OD_gauge.png")
imageData[37] = love.image.newImageData("asset/UI/matchScene/gauge/overdrive_indicator_gauge.png")
imageData[38] = love.image.newImageData("asset/UI/matchScene/gauge/risk_gauge.png")
imageData[39] = love.image.newImageData("asset/UI/matchScene/gauge/match_point_gauge.png")

love.thread.getChannel( 'image_1' ):push( imageData )